### ISSUE TITLE
Sandboxing not working

### ISSUE THREAD

**Issue by xtexChooser** [an-anime-team/flatpak-builds#50]
When using the flatpak build of sleepy-launcher:
```
xtex@xtex ~ (main)> flatpak run --allow=devel moe.launcher.sleepy-launcher
bwrap: No permissions to creating new namespace, likely because the kernel does not allow non-privileged user namespaces. On e.g. debian this can be enabled with 'sysctl kernel.unprivileged_userns_clone=1'.
```

However, my kernel (6.9.7-1-default from openSUSE Tumbleweed) says the sysctl given above does not exist:
```
xtex@xtex ~ (main)> sudo cat /proc/sys/kernel/unprivileged_userns_clone
cat: /proc/sys/kernel/unprivileged_userns_clone: No such file or directory
```

Disabling sandboxing solves this.

**Comment by Mar0xy** [comment]
I recommend asking on opensuse's mailing list or forum as this is mostly always related to either your specific opensuse install or due to how opensuse packages bwrap.
